### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by amiremami** [intrudir/BypassFuzzer#5]
Hey, thanks for your great tool! I'm new to your tool, it seems it's really complete, just wondering if it covers all the techniques used in this script too:

https://github.com/Dheerajmadhukar/4-ZERO-3/

Also, I wanted to know if you use case switching technique too?

https://redacted.com/admin -> 403 Forbidden
https://redacted.com/Admin -> 200 OK

🙏

Update: I noticed your script won't do URL ENCODING payloads for base domain, am I right?

**Comment by intrudir** [comment]
Hi @amiremami , pretty sure the tool does everything that one does. Yes i do camel casing and random uppers, and various other things. I encourage you to try it and see for yourself

no, i dont currently URL encode the base domain
